### ISSUE TITLE
[Bug]: IParameterViewStackService - InvalidOperationException: IView not registered

### ISSUE THREAD

**Issue by Dutch-0** [reactiveui/Sextant#764]
### Describe the bug 🐞

I'm currently migrating an app from Xamarin.Forms to Maui. When trying to resolve the `IParameterViewStackService` I get a `InvalidOperationException`:

```
Locator.Current.GetService<IParameterViewStackService>();
```

```
System.InvalidOperationException: IView not registered.
   at Sextant.DependencyResolverMixins.<>c.<RegisterParameterViewStackService>b__3_0() in /_/src/Sextant/DependencyResolverMixins.cs:line 61
   at Splat.DependencyResolverMixins.<>c__DisplayClass9_0`1[[Sextant.IParameterViewStackService, Sextant, Version=2.12.0.0, Culture=neutral, PublicKeyToken=null]].<RegisterLazySingleton>b__0() in /_/src/Splat/ServiceLocation/DependencyResolverMixins.cs:line 227
   at System.Lazy`1[[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1[[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1[[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateValue()
   at System.Lazy`1[[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Value()
   at Splat.DependencyResolverMixins.<>c__DisplayClass8_0.<RegisterLazySingleton>b__0() in /_/src/Splat/ServiceLocation/DependencyResolverMixins.cs:line 216
   at Splat.ModernDependencyResolver.<>c__DisplayClass6_0.<Register>b__0() in /_/src/Splat/ServiceLocation/ModernDependencyResolver.cs:line 85
   at Splat.ModernDependencyResolver.GetService(Type serviceType, String contract) in /_/src/Splat/ServiceLocation/ModernDependencyResolver.cs:line 137
   at Splat.DependencyResolverMixins.GetService[IParameterViewStackService](IReadonlyDependencyResolver resolver, String contract) in /_/src/Splat/ServiceLocation/DependencyResolverMixins.cs:line 32
   at MyApp.AppBootstrapper.CreateMainPage() in /home/user/RiderProjects/MyApp/MyApp/MyApp/MyApp/AppBootstrapper.cs:line 324
   at MyApp.App..ctor() in /home/user/RiderProjects/MyApp/MyApp/MyApp/MyApp/App.xaml.cs:line 53
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.Extensions.DependencyInjection.ServiceProvider.ServiceAccessor, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].GetOrAdd(ServiceIdentifier key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType) in D:\a\_work\1\s\src\Core\src\MauiContext.cs:line 72
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType) in D:\a\_work\1\s\src\Core\src\MauiContext.cs:line 72
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IApplication](IServiceProvider provider)
   at Microsoft.Maui.MauiApplication.OnCreate() in D:\a\_work\1\s\src\Core\src\Platform\Android\MauiApplication.cs:line 46
   at Android.App.Application.n_OnCreate(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.App.Application.cs:line 1086
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 26
```

### Step to reproduce

1. Register viewstack service: `Locator.CurrentMutable.RegisterParameterViewStackService();`
2. Try to resolve: `Locator.Current.GetService<IParameterViewStackService>();`

### Expected behavior

IParameterViewStackService should be resolved.

### Operating system

Linux

### Version

2.12.120

### ReactiveUI Version

19.5.41

**Comment by Dutch-0** [comment]
It was simply the wrong Sextant package which had been installed
